# Generated by Django 5.0 on 2023-12-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone_Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
