# Generated by Django 5.0 on 2023-12-13 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone_Book', '0002_alter_contact_name_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
